import { Tab } from '@headlessui/react'
import Head from 'next/head'
import Link from 'next/link'


const tabs = [
  {key : 'all', display: 'All'},
  {key : 'conceptual', display: 'Conceptual'},
  {key : 'dance', display: 'Dance'},
  {key : 'events', display: 'Events'},
  {key : 'crystal', display: 'Crystal'},
]

export default function Home() {
  return (
    <div className="flex flex-col h-full bg-stone-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between  items-center h-[90px] px-10 ">
        <div>Logo</div>
        <Link href="#" className="rounded-xl bg-white text-stone-700 px-5 py-2 hover:bg-opacity-90">       
         Get in Touch
        </Link>

      </header>

      <main className='grow'>
        <div className='flex  flex-col items-center h-full'> 
      <Tab.Group>
      <Tab.List className="flex justify-center gap-14">
          {tabs.map(tab => (
          <Tab key={tab.key} className="p-2"> 
          {({selected}) => 
          (<span className={selected ? 'text-white' : 'text-stone-400'}>{tab.display}</span>)}
        </Tab>
        ))}

      </Tab.List>
      <Tab.Panels className="bg-stone-900 bg-opacity-40 h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
        <Tab.Panel>All Photos</Tab.Panel>
        <Tab.Panel>Conceptual</Tab.Panel>
        <Tab.Panel>Dance</Tab.Panel>
        <Tab.Panel>Dance</Tab.Panel>
        <Tab.Panel>Dance</Tab.Panel>
        <Tab.Panel>Dance</Tab.Panel>
        <Tab.Panel>Dance</Tab.Panel>
      </Tab.Panels>
    </Tab.Group>
    </div>
      </main>


      <footer className='h-[60px] flex justify-center items-center'>
        <p>
        Logo
        </p></footer>
    </div>
  )
}
